import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>ToDo Challenge</title>
				<meta name='description' content='Generated by create next app' />
			</Head>

			<div>Hello World!</div>
		</div>
	);
};

export default Home;
